### ISSUE TITLE
Multiple Requests Simultaneously

### ISSUE THREAD

**Issue by ktmorris** [traveltime-dev/traveltime-sdk-r#37]
According to the API documentation on the TravelTime website, it seems like we should be able to make 10 requests at a time to the time_filter_fast endpoint. If I'm understanding this correctly (which I might not be), this would mean I could have 10 departure points, and measure how long it takes to get to, say, 100 destinations from each of them. Is this built into the R tool?

**Comment by EivydasKoc** [comment]
@ktmorris yes this functionality is available. See following example with 2 departure points:

`
locations <- c(
  make_location('London center', list(lat = 51.508930, lng = -0.131387)),
  make_location('Hyde Park', list(lat = 51.508824, lng = -0.167093)),
  make_location('ZSL London Zoo', list(lat = 51.536067, lng = -0.153596))
)

arrival_many_to_one <- 
  make_search(id = "arrive-at many-to-one search example",
              arrival_location_id = "London center",
              departure_location_ids = list("Hyde Park", "ZSL London Zoo"),
              travel_time = 1900,
              arrival_time_period = "weekday_morning",
              properties = list('travel_time', "fares"),
              transportation = list(type = "public_transport"))

arrival_one_to_many <- c(
  make_search(id = "arrive-at one-to-many search example 1",
              departure_location_id = "London center",
              arrival_location_ids = list("Hyde Park", "ZSL London Zoo"),
              travel_time = 1900,
              properties = list('travel_time', "fares"),
              arrival_time_period = "weekday_morning",
              transportation = list(type = "public_transport")),
  
  make_search(id = "arrive-at one-to-many search example 2",
              departure_location_id = "ZSL London Zoo",
              arrival_location_ids = list("London center", "Hyde Park"),
              travel_time = 1900,
              properties = list('travel_time', "fares"),
              arrival_time_period = "weekday_morning",
              transportation = list(type = "public_transport"))
)

result <- time_filter_fast(locations, arrival_many_to_one, arrival_one_to_many)

print(result)
`

You may concatenate up-to 10 searches (departure/arrival points).
